export const LIST_POSTS_REQUESTS ='LIST_POSTS_REQUESTS';
export const LIST_POSTS_SUCCESS = 'LIST_POSTS_SUCCESS';
export const LIST_POSTS_FAIL = 'LIST_POSTS_FAIL';
export const UPDATE_POSTS = 'UPDATE_POSTS';